name: Sub-Store
description: "支持 Surge 正式版的参数设置功能. 测落地功能 ability: http-client-policy, 同步配置的定时 cronexp: 55 23 * * *"
icon: https://raw.githubusercontent.com/cc63/ICON/main/Sub-Store.png
compat_arguments:
  ability: http-client-policy
  cronexp: 55 23 * * *
  sync: "Sub-Store Sync"
  timeout: 120
  engine: auto
  produce: "# Sub-Store Produce"
  produce_cronexp: 50 */6 * * *
  sync_success_notify: true
  produce_sub: "sub1,sub2"
  produce_col: "col1,col2"
  cors: "https://sub-store.vercel.app,http://substore.stash,https://substore.stash"
compat_arguments_desc: '\n1️⃣ ability\n\n默认已开启测落地能力\n需要配合脚本操作\n如 https://raw.githubusercontent.com/Keywos/rule/main/cname.js\n填写任意其他值关闭\n\n2️⃣ cronexp\n\n同步配置定时任务\n默认为每天 23 点 55 分\n\n定时任务指定时将订阅/文件上传到私有 Gist. 在前端, 叫做 ''同步'' 或 ''同步配置''\n\n3️⃣ sync\n\n自定义定时任务名\n便于在脚本编辑器中选择\n若设为 # 可取消定时任务\n\n4️⃣ timeout\n\n脚本超时, 单位为秒\n\n5️⃣ engine\n\n默认为自动使用 webview 引擎, 可设为指定 jsc, 但 jsc 容易爆内存\n\n6️⃣ produce\n\n自定义处理订阅的定时任务名\n一般用于定时处理耗时较长的订阅, 以更新缓存\n这样 Surge 中拉取的时候就能用到缓存, 不至于总是超时\n若设为 # 可取消此定时任务\n默认不开启\n\n7️⃣ produce_cronexp\n\n配置处理订阅的定时任务\n\n默认为每 6 小时\n\n8️⃣ sync_success_notify\n\n同步配置全部成功时是否发送完成通知\n默认为 true, 填 false/0/no/off 可关闭\n\n9️⃣ produce_sub\n\n自定义需定时处理的单条订阅名\n多个用 , 连接\n\n🔟 produce_col\n\n自定义需定时处理的组合订阅名\n多个用 , 连接\n\n1️⃣1️⃣ cors\n\n允许浏览器跨域访问 Sub-Store 后端的 origin. 默认为 https://sub-store.vercel.app,http://substore.stash,https://substore.stash. 多个用 , 连接. 设为 * 可恢复旧的任意来源访问行为, 存在钓鱼网站读取配置的风险\n\n⚠️ 注意: 是 名称(name) 不是 显示名称(displayName)\n如果名称需要编码, 请编码后再用 , 连接\n顺序: 并发执行单条订阅, 然后并发执行组合订阅'
scriptings:
  - http_request:
      name: Sub-Store Core
      match: ^https?:\/\/sub\.store\/((download)|api\/(preview|sync|(utils\/node-info)))
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-1.min.js
      body_required: true
      arguments:
        _compat.$argument: "cors={{{cors}}}"
  - http_request:
      name: Sub-Store Simple
      match: ^https?:\/\/sub\.store
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-0.min.js
      body_required: true
      arguments:
        _compat.$argument: "cors={{{cors}}}"
  - schedule:
      name: "{{{sync}}}"
      cron: "{{{cronexp}}}"
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/cron-sync-artifacts.min.js
      arguments:
        _compat.$argument: "sync_success_notify={{{sync_success_notify}}}"
  - schedule:
      name: "{{{produce}}}"
      cron: "{{{produce_cronexp}}}"
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/cron-sync-artifacts.min.js
      arguments:
        _compat.$argument: "sub={{{produce_sub}}}&col={{{produce_col}}}"
mitm:
  hostnames:
    includes:
      - sub.store
